name: travel_record_app
description: A mobile travel recording app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: NotoSans
#      fonts:
#        - asset: assets/fonts/NotoSansKR-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/NotoSansKR-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
#          weight: 600